### ISSUE TITLE
Check params by instanceof Date

### ISSUE THREAD

**Issue by fliptheweb** [nikitabulatov/finity-js#1]
<img width="1392" alt="screenshot 2017-01-17 15 14 53" src="https://cloud.githubusercontent.com/assets/308726/22012638/b7b74c44-dcc7-11e6-8aba-66891956c833.png">

**Comment by fliptheweb** [comment]
Why u don't answer me? =/
Is that library still alive?

**Comment by nikitabulatov** [comment]
Thank you for your patience, @fliptheweb https://github.com/nikitabulatov/finity-js/commit/83464496b1ba2d3e5ed205158c5d319e28c19d57
