### ISSUE TITLE
Request of down case formats

### ISSUE THREAD

**Issue by fliptheweb** [nikitabulatov/finity-js#2]
like `jan`, `feb`

**Comment by nikitabulatov** [comment]
@fliptheweb u can throw to "format" method your custom object of locale by 4th argument.
Like this: `finity.format(new Date(), 'MMM', false, monthsShort: ['jan', 'feb', ...])`.
And u can use ["setLocale" method](https://github.com/nikitabulatov/finity-js#setlocale)
